/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

//BMI Rechner

public class bmirechner {
    public static void main (String[] args) {
    Scanner scanner = new Scanner(System.in);

    System.out.println("Geben Sie Ihre KörperGröße in m ein:");
    double groesse = scanner.nextDouble();

    System.out.println("Geben Sie Ihr Gewicht in kg ein:");
    double gewicht = scanner.nextDouble();

    double bmi = gewicht / ((groesse) * (groesse));

    System.out.println("Ihr BMI ist " + bmi + ".");





    

    }
}